/* GENERATED by tools/feeltest.mjs — 3 hand-crafted meldburst feel-test
   boards. Replace with the factory's 50 levels once the core validates. */
(function(root,ls){ if(typeof module==="object"&&module.exports) module.exports=ls;
  else root.HUEMELD_LEVELS=ls; })(typeof self!=="undefined"?self:this,
[
  {
    "id": 1,
    "shape": [
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######"
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 2,
      "G": 1,
      "P": 1
    },
    "objectives": [
      {
        "color": "O",
        "count": 6
      }
    ],
    "moves": 6
  },
  {
    "id": 2,
    "shape": [
      ".##...##.",
      "#########",
      "#########",
      "#########",
      ".#######.",
      "..#####..",
      "...###...",
      "....#...."
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 1,
      "G": 2,
      "P": 1
    },
    "objectives": [
      {
        "color": "G",
        "count": 8
      }
    ],
    "moves": 7
  },
  {
    "id": 3,
    "shape": [
      "..####..",
      ".######.",
      "########",
      "########",
      "########",
      "########",
      ".######.",
      "..####.."
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 2,
      "G": 1,
      "P": 2
    },
    "objectives": [
      {
        "color": "O",
        "count": 6
      },
      {
        "color": "P",
        "count": 6
      }
    ],
    "moves": 9
  }
]);
