/* GENERATED by tools/factory.mjs — do not edit by hand. Move budgets are
   set by Monte-Carlo simulation so every level is winnable with margin. */
(function(root,ls){ if(typeof module==="object"&&module.exports) module.exports=ls;
  else root.HUEMELD_LEVELS=ls; })(typeof self!=="undefined"?self:this,
[
  {
    "id": 1,
    "name": "First strokes",
    "shape": [
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######"
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 1,
      "G": 1,
      "P": 1
    },
    "objectives": [
      {
        "color": "R",
        "count": 15
      }
    ],
    "moves": 14
  },
  {
    "id": 2,
    "name": "Two suns",
    "shape": [
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######"
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 1,
      "G": 1,
      "P": 1
    },
    "objectives": [
      {
        "color": "R",
        "count": 12
      },
      {
        "color": "Y",
        "count": 12
      }
    ],
    "moves": 13
  },
  {
    "id": 3,
    "name": "Orange grove",
    "shape": [
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######"
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 1,
      "G": 1,
      "P": 1
    },
    "objectives": [
      {
        "color": "O",
        "count": 6
      }
    ],
    "moves": 3
  },
  {
    "id": 4,
    "name": "Cut diamond",
    "shape": [
      "....#....",
      "...###...",
      "..#####..",
      ".#######.",
      "#########",
      ".#######.",
      "..#####..",
      "...###...",
      "....#...."
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 1,
      "G": 1,
      "P": 1
    },
    "objectives": [
      {
        "color": "B",
        "count": 14
      },
      {
        "color": "G",
        "count": 6
      }
    ],
    "moves": 18
  },
  {
    "id": 5,
    "name": "Crossroads",
    "shape": [
      "..###..",
      "..###..",
      "#######",
      "#######",
      "#######",
      "..###..",
      "..###.."
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 1,
      "G": 1,
      "P": 1
    },
    "objectives": [
      {
        "color": "O",
        "count": 6
      },
      {
        "color": "P",
        "count": 6
      }
    ],
    "moves": 7
  },
  {
    "id": 6,
    "name": "Sweetheart",
    "shape": [
      ".##...##.",
      "#########",
      "#########",
      "#########",
      ".#######.",
      "..#####..",
      "...###...",
      "....#...."
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 1,
      "G": 1,
      "P": 1
    },
    "objectives": [
      {
        "color": "R",
        "count": 14
      },
      {
        "color": "P",
        "count": 6
      }
    ],
    "moves": 17
  },
  {
    "id": 7,
    "name": "Pyramid",
    "shape": [
      "...#...",
      "..###..",
      ".#####.",
      "#######",
      "#######",
      "#######"
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 1,
      "G": 1,
      "P": 1
    },
    "objectives": [
      {
        "color": "Y",
        "count": 12
      },
      {
        "color": "G",
        "count": 5
      }
    ],
    "moves": 18
  },
  {
    "id": 8,
    "name": "Prism finale",
    "shape": [
      "..####..",
      ".######.",
      "########",
      "########",
      "########",
      "########",
      ".######.",
      "..####.."
    ],
    "spawn": {
      "R": 4,
      "Y": 4,
      "B": 4,
      "O": 1,
      "G": 1,
      "P": 1
    },
    "objectives": [
      {
        "color": "O",
        "count": 6
      },
      {
        "color": "G",
        "count": 6
      },
      {
        "color": "P",
        "count": 6
      }
    ],
    "moves": 7
  }
]);
