/* Level design factory.
   Pairs board shapes with objectives, then uses the Monte-Carlo solver to set a
   fair, winnable move budget for each, and writes ../levels.js.
   Run:  node huemeld/tools/factory.mjs           (writes levels.js + prints report)
         node huemeld/tools/factory.mjs --dry      (report only) */
import { createRequire } from "module";
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
const require = createRequire(import.meta.url);
const HM = require("../engine.js");
import { estimate, winRate } from "./simulate.mjs";

const __dir = dirname(fileURLToPath(import.meta.url));

/* ---- shape library (# = playable, . = wall). Various forms, not just rectangles ---- */
const S = {
  rect7: ["#######", "#######", "#######", "#######", "#######", "#######", "#######"],
  rect78: ["#######", "#######", "#######", "#######", "#######", "#######", "#######", "#######"],
  diamond: [
    "....#....", "...###...", "..#####..", ".#######.", "#########",
    ".#######.", "..#####..", "...###...", "....#...."
  ],
  plus: ["..###..", "..###..", "#######", "#######", "#######", "..###..", "..###.."],
  octagon: ["..####..", ".######.", "########", "########", "########", "########", ".######.", "..####.."],
  heart: [
    ".##...##.", "#########", "#########", "#########", ".#######.", "..#####..", "...###...", "....#...."
  ],
  pyramid: ["...#...", "..###..", ".#####.", "#######", "#######", "#######"]
};

const W = { R: 4, Y: 4, B: 4, O: 1, G: 1, P: 1 };   // primaries common, blends rare

/* ---- level specs (move budget filled in by the solver) ---- */
const SPECS = [
  { name: "First strokes", shape: S.rect7, spawn: W, objectives: [{ color: "R", count: 15 }] },
  { name: "Two suns", shape: S.rect78, spawn: W, objectives: [{ color: "R", count: 12 }, { color: "Y", count: 12 }] },
  { name: "Orange grove", shape: S.rect78, spawn: W, objectives: [{ color: "O", count: 6 }] },
  { name: "Cut diamond", shape: S.diamond, spawn: W, objectives: [{ color: "B", count: 14 }, { color: "G", count: 6 }] },
  { name: "Crossroads", shape: S.plus, spawn: W, objectives: [{ color: "O", count: 6 }, { color: "P", count: 6 }] },
  { name: "Sweetheart", shape: S.heart, spawn: W, objectives: [{ color: "R", count: 14 }, { color: "P", count: 6 }] },
  { name: "Pyramid", shape: S.pyramid, spawn: W, objectives: [{ color: "Y", count: 12 }, { color: "G", count: 5 }] },
  { name: "Prism finale", shape: S.octagon, spawn: W, objectives: [{ color: "O", count: 6 }, { color: "G", count: 6 }, { color: "P", count: 6 }] }
];

const FLOOR = 8;

/* Budget = median moves-to-win with headroom. The ε-random sim has a heavy tail
   (occasional flailing runs) that a human never has, so we cap the tail's
   influence at ~2.2x the median rather than chasing the sim's own win-rate. */
function tune(spec) {
  const est = estimate(spec, 200, 11);
  const p50 = isFinite(est.p50) ? est.p50 : est.mean;
  const budget = Math.max(FLOOR, Math.round(p50 * 2));   // ~2x median competent solve: generous, feasible
  const wr = winRate(spec, budget, 150, 7001);           // reported as a (pessimistic) sanity check
  return { est, budget, winRate: wr };
}

const dry = process.argv.includes("--dry");
const out = [];
const rows = [];
let id = 1;
process.stdout.write("  simulating (150 trials/level)...\n");
for (const spec of SPECS) {
  const play = HM.playableCount(HM.newState({ ...spec, moves: 1 }));
  const t = tune(spec);
  console.log("  · " + spec.name.padEnd(15) + " -> " + String(t.budget).padStart(3) + " moves   (p50 " +
    String(t.est.p50).padStart(3) + ", p80 " + String(t.est.p80).padStart(3) + ", solves " +
    (t.est.finishRate * 100).toFixed(0) + "%, win@budget " + (t.winRate * 100).toFixed(0) + "%)");
  const objStr = spec.objectives.map(o => `${o.count}${o.color}`).join(" + ");
  rows.push({
    id, name: spec.name, cells: play, obj: objStr,
    finish: (t.est.finishRate * 100).toFixed(0) + "%",
    p50: t.est.p50, p80: t.est.p80, moves: t.budget, win: (t.winRate * 100).toFixed(0) + "%"
  });
  out.push({ id, name: spec.name, shape: spec.shape, spawn: spec.spawn, objectives: spec.objectives, moves: t.budget });
  id++;
}

console.log("\n  Huemeld level report (greedy Monte-Carlo, 200 trials each)\n");
console.log("  #  name            cells  objectives      solve%  p50  p80  MOVES  win@budget");
console.log("  " + "-".repeat(76));
for (const r of rows) {
  console.log(
    "  " + String(r.id).padEnd(3) + r.name.padEnd(16) + String(r.cells).padEnd(7) +
    r.obj.padEnd(16) + r.finish.padEnd(8) + String(r.p50).padEnd(5) + String(r.p80).padEnd(5) +
    String(r.moves).padEnd(7) + r.win
  );
}
console.log("");

if (!dry) {
  const banner = "/* GENERATED by tools/factory.mjs — do not edit by hand. Move budgets are\n" +
    "   set by Monte-Carlo simulation so every level is winnable with margin. */\n";
  const body =
    "(function(root,ls){ if(typeof module===\"object\"&&module.exports) module.exports=ls;\n" +
    "  else root.HUEMELD_LEVELS=ls; })(typeof self!==\"undefined\"?self:this,\n" +
    JSON.stringify(out, null, 2) + ");\n";
  writeFileSync(join(__dir, "..", "levels.js"), banner + body);
  console.log("  wrote ../levels.js (" + out.length + " levels)\n");
}
