/* Feel-test build: writes THREE hand-crafted boards to ../levels.js so the
   meldburst core can be validated in hand before the full 50-level factory
   run. Per the design's build order: a rejected feel costs an afternoon,
   a rejected 50-level retune costs an iteration.
   Run:  node huemeld/tools/feeltest.mjs */
import { createRequire } from "module";
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
const require = createRequire(import.meta.url);
const HM = require("../engine.js");
import { estimate, winRate } from "./simulate.mjs";

const __dir = dirname(fileURLToPath(import.meta.url));

const rect7 = ["#######", "#######", "#######", "#######", "#######", "#######", "#######"];
const heart = [".##...##.", "#########", "#########", "#########", ".#######.", "..#####..", "...###...", "....#...."];
const octagon = ["..####..", ".######.", "########", "########", "########", "########", ".######.", "..####.."];

/* juicy circle weights (2, never 3 — deadlock risk) on the colours each
   board wants you to hunt, so treasure is reliably on the table */
const SPECS = [
  { shape: rect7, spawn: { R: 4, Y: 4, B: 4, O: 2, G: 1, P: 1 }, objectives: [{ color: "O", count: 6 }] },
  { shape: heart, spawn: { R: 4, Y: 4, B: 4, O: 1, G: 2, P: 1 }, objectives: [{ color: "G", count: 8 }] },
  { shape: octagon, spawn: { R: 4, Y: 4, B: 4, O: 2, G: 1, P: 2 }, objectives: [{ color: "O", count: 6 }, { color: "P", count: 6 }] }
];

/* Feel-test budgets are deliberately GENEROUS — the goal is to let the
   player explore the mechanic and reach the win fireworks with room to make
   sub-optimal moves, not to squeeze them. So we escalate until even the
   middling "aware" policy (fuses needed recipes but ignores treasure) wins
   comfortably. The real 50-level factory tunes tight against greedy instead. */
const TARGET_WIN = 0.9;   // vs the AWARE rail, not greedy

const out = [];
let id = 1;
console.log("  feel-test boards (generous budget — aware policy wins >=90%)\n");
for (const spec of SPECS) {
  const est = estimate(spec, 200, 11);
  let budget = Math.max(6, Math.ceil(est.p80 * 1.4));
  let wr = winRate(spec, budget, 150, 7001, "aware"), guard = 0;
  while (wr < TARGET_WIN && guard++ < 30) { budget++; wr = winRate(spec, budget, 150, 7001, "aware"); }
  const greedy = winRate(spec, budget, 150, 7001, "greedy");
  const masher = winRate(spec, budget, 150, 9001, "masher");
  const aware = wr;
  const objStr = spec.objectives.map(o => `${o.count}${o.color}`).join(" + ");
  console.log("  #" + id + "  " + objStr.padEnd(10) + " p50 " + est.p50 + "  p80 " + est.p80 +
    "  -> " + budget + " moves   win: greedy " + (greedy * 100).toFixed(0) + "%  aware " +
    (aware * 100).toFixed(0) + "%  masher " + (masher * 100).toFixed(0) + "%");
  out.push({ id, shape: spec.shape, spawn: spec.spawn, objectives: spec.objectives, moves: budget });
  id++;
}

const banner = "/* GENERATED by tools/feeltest.mjs — 3 hand-crafted meldburst feel-test\n" +
  "   boards. Replace with the factory's 50 levels once the core validates. */\n";
const body =
  "(function(root,ls){ if(typeof module===\"object\"&&module.exports) module.exports=ls;\n" +
  "  else root.HUEMELD_LEVELS=ls; })(typeof self!==\"undefined\"?self:this,\n" +
  JSON.stringify(out, null, 2) + ");\n";
writeFileSync(join(__dir, "..", "levels.js"), banner + body);
console.log("\n  wrote ../levels.js (" + out.length + " feel-test boards)\n");
