/* Feel-test build: writes THREE hand-crafted boards to ../levels.js so the
   meldburst core can be validated in hand before the full 50-level factory
   run. Per the design's build order: a rejected feel costs an afternoon,
   a rejected 50-level retune costs an iteration.
   Run:  node huemeld/tools/feeltest.mjs */
import { createRequire } from "module";
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
const require = createRequire(import.meta.url);
const HM = require("../engine.js");
import { estimate, winRate } from "./simulate.mjs";

const __dir = dirname(fileURLToPath(import.meta.url));

const rect7 = ["#######", "#######", "#######", "#######", "#######", "#######", "#######"];
const heart = [".##...##.", "#########", "#########", "#########", ".#######.", "..#####..", "...###...", "....#...."];
const octagon = ["..####..", ".######.", "########", "########", "########", "########", ".######.", "..####.."];

/* Bigger objective targets so the tuned budget lands at a comfortable size
   (the designer wants a ~15-move floor, not tiny budgets). Each meld makes
   roughly one secondary, so a ~14-20 target naturally needs ~15-24 moves.
   Juicy circle weights (2, never 3 — deadlock risk) put a little treasure on
   the board for free sweeps. */
const SPECS = [
  { shape: rect7, spawn: { R: 4, Y: 4, B: 4, O: 2, G: 1, P: 1 }, objectives: [{ color: "O", count: 14 }] },
  { shape: heart, spawn: { R: 4, Y: 4, B: 4, O: 1, G: 2, P: 1 }, objectives: [{ color: "G", count: 16 }] },
  { shape: octagon, spawn: { R: 4, Y: 4, B: 4, O: 2, G: 1, P: 2 }, objectives: [{ color: "O", count: 10 }, { color: "P", count: 10 }] }
];

const FLOOR = 15;         // no tiny budgets — raise the target instead of squeezing moves
const TARGET_WIN = 0.9;   // generous: the greedy policy should win comfortably so the player can explore

const out = [];
let id = 1;
console.log("  feel-test boards (floor " + FLOOR + " moves, greedy win >= " + (TARGET_WIN * 100) + "%)\n");
for (const spec of SPECS) {
  const est = estimate(spec, 200, 11);
  let budget = Math.max(FLOOR, Math.ceil(est.p80 * 1.35));
  let wr = winRate(spec, budget, 150, 7001), guard = 0;
  while (wr < TARGET_WIN && guard++ < 40) { budget++; wr = winRate(spec, budget, 150, 7001); }
  const objStr = spec.objectives.map(o => `${o.count}${o.color}`).join(" + ");
  console.log("  #" + id + "  " + objStr.padEnd(12) + " p50 " + est.p50 + "  p80 " + est.p80 +
    "  -> " + budget + " moves   greedy win " + (wr * 100).toFixed(0) + "%");
  out.push({ id, shape: spec.shape, spawn: spec.spawn, objectives: spec.objectives, moves: budget });
  id++;
}

const banner = "/* GENERATED by tools/feeltest.mjs — 3 hand-crafted meldburst feel-test\n" +
  "   boards. Replace with the factory's 50 levels once the core validates. */\n";
const body =
  "(function(root,ls){ if(typeof module===\"object\"&&module.exports) module.exports=ls;\n" +
  "  else root.HUEMELD_LEVELS=ls; })(typeof self!==\"undefined\"?self:this,\n" +
  JSON.stringify(out, null, 2) + ");\n";
writeFileSync(join(__dir, "..", "levels.js"), banner + body);
console.log("\n  wrote ../levels.js (" + out.length + " feel-test boards)\n");
