/* Produce the full app dataset: a ramped campaign + a daily-puzzle pool, each
   level proven-unique and carrying baked hint paths (the delivery structure for
   every circle). Writes ../flow-data.js -> window.HUEMELD_FLOW = {campaign,daily}.

   Run: node huemeld/tools/flow-app.mjs [--seed N] */
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { genGate, mulberry32 } from "./flow-gen2.mjs";
import { countSolutions, findOneSolution } from "./flow-solve.mjs";
import { deliveriesByTarget } from "./flow-hints.mjs";

const __dir = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const seed = +(args.indexOf("--seed") >= 0 ? args[args.indexOf("--seed") + 1] : 20260712) || 20260712;
const rng = mulberry32(seed);

/* Clean single-emitter boards (one R/Y/B square each, free to fork) with secondary
   circles as objectives and COLOUR GATES for challenge. "junction" = 2 emitters +
   1 mix; "fork" = 3 emitters + 2 mixes. Boards are (near-)full — walls stay sparse. */
const SOL = { campaign: [], daily: [] };   // constructed solution edges, per level (for the verifier)
function makeLevel(base) {
  const g = genGate({ tries: 6000, ...base }, rng);
  if (!g) return null;
  const L = g.L;
  // hints come straight from the CONSTRUCTED solution (g.edges) — no need to solve.
  const hints = deliveriesByTarget(L, g.edges).map((d) => d.cells);
  return { lv: { n: L.n, sq: L.sq, ci: L.ci, walls: L.walls || [], gates: L.gates, hints }, edges: g.edges };
}

function buildSet(ramp, label) {
  const set = []; const sigs = new Set();
  const t0 = Date.now();
  for (const [count, base] of ramp) {
    let made = 0, attempts = 0;
    while (made < count && attempts < count * 120) {
      attempts++;
      const r = makeLevel(base);
      if (!r) continue;
      const lv = r.lv;
      const sig = JSON.stringify([lv.n, lv.sq, lv.ci, lv.walls, lv.gates]);
      if (sigs.has(sig)) continue;
      sigs.add(sig); set.push(lv); SOL[label].push({ lv, edges: r.edges }); made++;
    }
    if (made < count) process.stderr.write(`  (${label} tier short ${made}/${count} n${base.n} ${base.type})\n`);
  }
  const walls = set.reduce((a, l) => a + l.walls.length, 0) / (set.length || 1);
  process.stderr.write(`${label}: ${set.length} levels, avg walls ${walls.toFixed(1)}, ${Math.round((Date.now() - t0) / 1000)}s\n`);
  return set;
}

// campaign — learn one mix, then the fork; gates scale up; walls stay sparse
const CAMPAIGN = [
  // Tier 1 — one mix on a full 5×5, a single gate to start
  [3, { n: 5, type: "junction", minOpen: 25, gates: 1 }],
  [3, { n: 5, type: "junction", minOpen: 24, gates: 2 }],
  // Tier 2 — bigger single-mix boards
  [4, { n: 6, type: "junction", minOpen: 34, looseness: 0.9, gates: 2 }],
  // Tier 3 — the fork: one square feeds two mixes (2 secondaries)
  [4, { n: 6, type: "fork", minOpen: 32, looseness: 1.0, gates: 2 }],
  [4, { n: 7, type: "fork", minOpen: 45, looseness: 1.0, gates: 3 }],
  // Tier 4 — bigger forks, more gates (make you think)
  [5, { n: 7, type: "fork", minOpen: 45, looseness: 1.0, gates: 4 }],
  [4, { n: 7, type: "fork", minOpen: 46, looseness: 1.0, gates: 5 }],
];

// daily pool — a spread of self-contained medium puzzles
const DAILY = [
  [30, { n: 6, type: "junction", minOpen: 35, looseness: 0.9, gates: 2 }],
  [30, { n: 6, type: "fork", minOpen: 32, looseness: 1.0, gates: 3 }],
  [30, { n: 7, type: "fork", minOpen: 45, looseness: 1.0, gates: 3 }],
];

const campaign = buildSet(CAMPAIGN, "campaign");
const daily = buildSet(DAILY, "daily");

// levels are solvable by construction; end-to-end winnability is verified
// separately by replaying each through the real engine.
void countSolutions; void findOneSolution;

const payload = { version: 3, campaign, daily };
const js = "/* GENERATED by tools/flow-app.mjs — single-emitter gate puzzles with baked hints. */\n" +
  "window.HUEMELD_FLOW=" + JSON.stringify(payload) + ";\n";
writeFileSync(join(__dir, "..", "flow-data.js"), js);
// sidecar for the engine-replay verifier (NOT shipped): levels + their solution edges
if (args.indexOf("--solfile") >= 0) writeFileSync(args[args.indexOf("--solfile") + 1], JSON.stringify(SOL));
process.stderr.write(`wrote ../flow-data.js  campaign=${campaign.length} daily=${daily.length}  ${(js.length / 1024 | 0)}KB\n`);
