/* Produce the full app dataset: a ramped campaign + a daily-puzzle pool, each
   level proven-unique and carrying baked hint paths (the delivery structure for
   every circle). Writes ../flow-data.js -> window.HUEMELD_FLOW = {campaign,daily}.

   Run: node huemeld/tools/flow-app.mjs [--seed N] */
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { genSpider, mulberry32 } from "./flow-gen2.mjs";
import { countSolutions, findOneSolution } from "./flow-solve.mjs";
import { deliveriesByTarget } from "./flow-hints.mjs";

const __dir = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const seed = +(args.indexOf("--seed") >= 0 ? args[args.indexOf("--seed") + 1] : 20260710) || 20260710;
const rng = mulberry32(seed);
const BUDGET = 150_000;

/* Levels are single-emitter (one R/Y/B square each, free to fork), with secondary
   circles as objectives. "junction" = 2 emitters + 1 mix; "fork" = 3 emitters +
   2 mixes (one square forks). */
function makeLevel(base) {
  const g = genSpider({ ...base, tries: base.tries || 600 }, rng, BUDGET);
  if (!g) return null;
  const sol = findOneSolution(g.L, 2_000_000);
  if (!sol) return null;
  const hints = deliveriesByTarget(g.L, sol).map((d) => d.cells);
  return { n: g.L.n, sq: g.L.sq, ci: g.L.ci, walls: g.L.walls || [], hints };
}

function buildSet(ramp, label) {
  const set = []; const sigs = new Set();
  const t0 = Date.now();
  for (const [count, base] of ramp) {
    let made = 0, attempts = 0;
    while (made < count && attempts < count * 80) {
      attempts++;
      const lv = makeLevel(base);
      if (!lv) continue;
      const sig = JSON.stringify([lv.n, lv.sq, lv.ci, lv.walls]);
      if (sigs.has(sig)) continue;
      sigs.add(sig); set.push(lv); made++;
    }
    if (made < count) process.stderr.write(`  (${label} tier short ${made}/${count} n${base.n} j${base.junctions})\n`);
  }
  process.stderr.write(`${label}: ${set.length} levels in ${Math.round((Date.now() - t0) / 1000)}s\n`);
  return set;
}

// campaign — learn the single mix, then forks, on bigger boards
const CAMPAIGN = [
  // Tier 1 — one mix: two squares meet, blend to their ✦
  [4, { n: 5, type: "junction", minOpen: 12 }],
  [4, { n: 6, type: "junction", minOpen: 16 }],
  [4, { n: 6, type: "junction", minOpen: 20, looseness: 0.2 }],
  // Tier 2 — bigger single-mix boards
  [4, { n: 7, type: "junction", minOpen: 24, looseness: 0.2 }],
  // Tier 3 — the fork: one square feeds two mixes
  [5, { n: 6, type: "fork", minOpen: 18 }],
  [5, { n: 7, type: "fork", minOpen: 24, looseness: 0.2 }],
  // Tier 4 — hard forks, big boards (make you think)
  [5, { n: 8, type: "fork", minOpen: 30, looseness: 0.2 }],
  [4, { n: 8, type: "fork", minOpen: 36, looseness: 0.3 }],
];

// daily pool — a spread of self-contained medium puzzles
const DAILY = [
  [25, { n: 6, type: "junction", minOpen: 18, looseness: 0.2 }],
  [25, { n: 7, type: "fork", minOpen: 24, looseness: 0.2 }],
  [25, { n: 7, type: "junction", minOpen: 26, looseness: 0.25 }],
  [15, { n: 8, type: "fork", minOpen: 32, looseness: 0.2 }],
];

const campaign = buildSet(CAMPAIGN, "campaign");
const daily = buildSet(DAILY, "daily");

// final re-verification
let bad = 0;
for (const s of [campaign, daily]) for (const lv of s) { const r = countSolutions(lv, 2, 2_000_000); if (r.aborted || r.count !== 1) bad++; }
process.stderr.write(`re-verify: ${bad} non-unique (want 0)\n`);

const payload = { version: 2, campaign, daily };
const js = "/* GENERATED by tools/flow-app.mjs — proven-unique levels with baked hints. */\n" +
  "window.HUEMELD_FLOW=" + JSON.stringify(payload) + ";\n";
writeFileSync(join(__dir, "..", "flow-data.js"), js);
process.stderr.write(`wrote ../flow-data.js  campaign=${campaign.length} daily=${daily.length}  ${(js.length / 1024 | 0)}KB\n`);
