/* Produce the full app dataset: a ramped campaign + a daily-puzzle pool, each
   level proven-unique and carrying baked hint paths (the delivery structure for
   every circle). Writes ../flow-data.js -> window.HUEMELD_FLOW = {campaign,daily}.

   Run: node huemeld/tools/flow-app.mjs [--seed N] */
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { genUnique, mulberry32 } from "./flow-gen.mjs";
import { countSolutions, findOneSolution } from "./flow-solve.mjs";
import { deliveriesByTarget } from "./flow-hints.mjs";

const __dir = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const seed = +(args.indexOf("--seed") >= 0 ? args[args.indexOf("--seed") + 1] : 20260709) || 20260709;
const rng = mulberry32(seed);
const BUDGET = 130_000;

const interiorWalls = (n, count) => (r) => {
  const s = new Set(); let g = 0;
  while (s.size < count && g++ < 80) { const rr = 1 + ((r() * (n - 2)) | 0), cc = 1 + ((r() * (n - 2)) | 0); s.add(rr + "," + cc); }
  return s;
};

function makeLevel(base) {
  const spec = {
    n: base.n, junctions: base.junctions, minSeg: base.minSeg, maxSeg: base.maxSeg, tries: 60,
    makeWalls: base.walls ? interiorWalls(base.n, base.walls) : null,
  };
  const g = genUnique(spec, rng, BUDGET);
  if (!g) return null;
  const sol = findOneSolution(g.L, 2_000_000);
  if (!sol) return null;
  const hints = deliveriesByTarget(g.L, sol).map((d) => d.cells);
  return { n: g.L.n, sq: g.L.sq, ci: g.L.ci, walls: g.L.walls || [], hints };
}

function buildSet(ramp, label) {
  const set = []; const sigs = new Set();
  const t0 = Date.now();
  for (const [count, base] of ramp) {
    let made = 0, attempts = 0;
    while (made < count && attempts < count * 80) {
      attempts++;
      const lv = makeLevel(base);
      if (!lv) continue;
      const sig = JSON.stringify([lv.n, lv.sq, lv.ci, lv.walls]);
      if (sigs.has(sig)) continue;
      sigs.add(sig); set.push(lv); made++;
    }
    if (made < count) process.stderr.write(`  (${label} tier short ${made}/${count} n${base.n} j${base.junctions})\n`);
  }
  process.stderr.write(`${label}: ${set.length} levels in ${Math.round((Date.now() - t0) / 1000)}s\n`);
  return set;
}

// campaign — a longer version of the shipped ramp
const CAMPAIGN = [
  [3, { n: 5, junctions: 0, minSeg: 5, maxSeg: 8, walls: 1 }],
  [3, { n: 5, junctions: 0, minSeg: 4, maxSeg: 7, walls: 2 }],
  [3, { n: 6, junctions: 0, minSeg: 5, maxSeg: 9, walls: 2 }],
  [4, { n: 5, junctions: 1, minSeg: 2, maxSeg: 4, walls: 2 }],
  [4, { n: 6, junctions: 1, minSeg: 2, maxSeg: 4, walls: 3 }],
  [5, { n: 6, junctions: 2, minSeg: 2, maxSeg: 4, walls: 4 }],
  [5, { n: 6, junctions: 2, minSeg: 2, maxSeg: 3, walls: 5 }],
  [6, { n: 7, junctions: 2, minSeg: 2, maxSeg: 4, walls: 6 }],
  [6, { n: 7, junctions: 3, minSeg: 2, maxSeg: 4, walls: 7 }],
  [5, { n: 7, junctions: 3, minSeg: 2, maxSeg: 3, walls: 8 }],
  // hard tier — dense mixing, tight boards (make you think)
  [5, { n: 7, junctions: 3, minSeg: 2, maxSeg: 3, walls: 9 }],
  [4, { n: 7, junctions: 4, minSeg: 2, maxSeg: 3, walls: 9 }],
];

// daily pool — a spread of self-contained "one satisfying puzzle" boards (medium)
const DAILY = [
  [30, { n: 6, junctions: 1, minSeg: 2, maxSeg: 4, walls: 3 }],
  [30, { n: 6, junctions: 2, minSeg: 2, maxSeg: 4, walls: 4 }],
  [30, { n: 7, junctions: 2, minSeg: 2, maxSeg: 4, walls: 6 }],
];

const campaign = buildSet(CAMPAIGN, "campaign");
const daily = buildSet(DAILY, "daily");

// final re-verification
let bad = 0;
for (const s of [campaign, daily]) for (const lv of s) { const r = countSolutions(lv, 2, 2_000_000); if (r.aborted || r.count !== 1) bad++; }
process.stderr.write(`re-verify: ${bad} non-unique (want 0)\n`);

const payload = { version: 2, campaign, daily };
const js = "/* GENERATED by tools/flow-app.mjs — proven-unique levels with baked hints. */\n" +
  "window.HUEMELD_FLOW=" + JSON.stringify(payload) + ";\n";
writeFileSync(join(__dir, "..", "flow-data.js"), js);
process.stderr.write(`wrote ../flow-data.js  campaign=${campaign.length} daily=${daily.length}  ${(js.length / 1024 | 0)}KB\n`);
